label_dict = {
    "qcd_old": {"legend": "QCD", "label": "fj_isQCD"},
    "qcd": {"legend": "QCD", "label": "fj_QCD_label"},
    "qcdnolep": {"legend": "QCD", "label": "fj_QCD_label"},
    "top": {"legend": "Top", "label": "fj_isTop_label"},
    "top_lep": {"legend": "Top lep", "label": "fj_isToplep"},
    "top_merged": {"legend": "Top merged", "label": "fj_isTop_merged"},
    "top_semimerged": {"legend": "Top semi-merged", "label": "fj_isTop_semimerged"},
    "top_lepmerged": {"legend": "Top merged lepton", "label": "fj_isToplep_merged"},
    "hww_4q": {"legend": "H(VV) all-had", "label": "fj_H_VV_4q"},
    "hww_4q_merged": {"legend": "H(VV) 4q", "label": "fj_H_VV_4q_4q"},
    "hww_3q_merged": {"legend": "H(VV) 3q", "label": "fj_H_VV_4q_3q"},
    "hbb": {"legend": "H(bb)", "label": "fj_H_bb"},
    "hww_elenuqq": {"legend": "H(VV) ele", "label": "fj_H_VV_elenuqq"},
    "hww_munuqq": {"legend": "H(VV) mu", "label": "fj_H_VV_munuqq"},
    "hww_taunuqq": {"legend": "H(VV) tau merged", "label": "fj_isHVV_taunuqq_merged"},
    "hww_munuqq_merged": {"legend": "H(VV) mu merged", "label": "fj_isHVV_munuqq_merged"},
    "hww_munuqq_semimerged": {
        "legend": "H(VV) mu semi-merged",
        "label": "fj_isHVV_munuqq_semimerged",
    },
    "hww_elenuqq_merged": {"legend": "H(VV) ele merged", "label": "fj_isHVV_elenuqq_merged"},
    "hww_elenuqq_semimerged": {
        "legend": "H(VV) ele semi-merged",
        "label": "fj_isHVV_elenuqq_semimerged",
    },
    "hww_taunuqq_merged": {"legend": "H(VV) tau merged", "label": "fj_isHVV_taunuqq_merged"},
    "hww_taunuqq_semimerged": {
        "legend": "H(VV) tau semi-merged",
        "label": "fj_isHVV_taunuqq_semimerged",
    },
    "hww_4q_dnn": {"legend": "H(VV) 4q", "label": "label_H_ww4q"},
    "hww_3q_dnn": {"legend": "H(VV) 3q", "label": "label_H_ww3q"},
    "hww_lvqq_dnn": {"legend": "H(VV) lvqq", "label": "label_H_wwlvqq"},
    "hww_ltvqq_dnn": {"legend": "H(VV) ltvqq", "label": "label_H_wwleptauvqq"},
    "hww_htvqq_dnn": {"legend": "H(VV) htvqq", "label": "label_H_wwhadtauvqq"},
    "hww_evqq_dnn": {"legend": "H(VV) evqq", "label": "label_H_wwevqq"},
    "hww_mvqq_dnn": {"legend": "H(VV) mvqq", "label": "label_H_wwmvqq"},
    "hww_etvqq_dnn": {"legend": "H(VV) etvqq", "label": "label_H_wwleptauevqq"},
    "hww_mtvqq_dnn": {"legend": "H(VV) mtvqq", "label": "label_H_wwleptaumvqq"},
    "qcd_dnn": {"legend": "QCD", "label": "fj_QCD_label"},
}


label_dict_old = {
    "qcd_old": {"legend": "QCD", "label": "fj_isQCD"},
    "qcd": {"legend": "QCD", "label": "fj_QCD_label"},
    "top": {"legend": "Top", "label": "fj_isTop_label"},
    "top_lep": {"legend": "Top lep", "label": "fj_isToplep"},
    "top_merged": {"legend": "Top merged", "label": "fj_isTop_merged"},
    "top_semimerged": {"legend": "Top semi-merged", "label": "fj_isTop_semimerged"},
    "top_lepmerged": {"legend": "Top merged lepton", "label": "fj_isToplep_merged"},
    "hww_4q": {"legend": "H(WW) all-had", "label": "fj_H_WW_4q"},
    "hww_4q_merged": {"legend": "H(WW) 4q", "label": "fj_H_WW_4q_4q"},
    "hww_3q_merged": {"legend": "H(WW) 3q", "label": "fj_H_WW_4q_3q"},
    "hbb": {"legend": "H(bb)", "label": "fj_H_bb"},
    "hww_elenuqq": {"legend": "H(WW) ele", "label": "fj_H_WW_elenuqq"},
    "hww_munuqq": {"legend": "H(WW) mu", "label": "fj_H_WW_munuqq"},
    "hww_taunuqq": {"legend": "H(WW) tau merged", "label": "fj_isHWW_taunuqq_merged"},
    "hww_munuqq_merged": {"legend": "H(WW) mu merged", "label": "fj_isHWW_munuqq_merged"},
    "hww_munuqq_semimerged": {
        "legend": "H(WW) mu semi-merged",
        "label": "fj_isHWW_munuqq_semimerged",
    },
    "hww_elenuqq_merged": {"legend": "H(WW) ele merged", "label": "fj_isHWW_elenuqq_merged"},
    "hww_elenuqq_semimerged": {
        "legend": "H(WW) ele semi-merged",
        "label": "fj_isHWW_elenuqq_semimerged",
    },
    "hww_taunuqq_merged": {"legend": "H(WW) tau merged", "label": "fj_isHWW_taunuqq_merged"},
    "hww_taunuqq_semimerged": {
        "legend": "H(WW) tau semi-merged",
        "label": "fj_isHWW_taunuqq_semimerged",
    },
    "hww_4q_dnn": {"legend": "H(WW) 4q", "label": "label_H_ww4q"},
    "hww_3q_dnn": {"legend": "H(WW) 3q", "label": "label_H_ww3q"},
    "hww_lvqq_dnn": {"legend": "H(WW) lvqq", "label": "label_H_wwlvqq"},
    "hww_ltvqq_dnn": {"legend": "H(WW) ltvqq", "label": "label_H_wwleptauvqq"},
    "hww_htvqq_dnn": {"legend": "H(WW) htvqq", "label": "label_H_wwhadtauvqq"},
    "hww_evqq_dnn": {"legend": "H(WW) evqq", "label": "label_H_wwevqq"},
    "hww_mvqq_dnn": {"legend": "H(WW) mvqq", "label": "label_H_wwmvqq"},
    "hww_etvqq_dnn": {"legend": "H(WW) etvqq", "label": "label_H_wwleptauevqq"},
    "hww_mtvqq_dnn": {"legend": "H(WW) mtvqq", "label": "label_H_wwleptaumvqq"},
    "qcd_dnn": {"legend": "QCD", "label": "fj_QCD_label"},
}
